---
- name: Create random password
  hosts: localhost
  vars_files: vars/vars_password.yml
  tasks:
  - set_fact:
       org_password: "{{ my_pass|shuffle|join() }}"

  - debug:
       msg: "{{ org_password }}"
  
